services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin

    ports:
      - "8096:8096"

    volumes:
      - ./config:/config
      - ./cache:/cache
      - "/mnt/media:/media"

    environment:
      - TZ=Asia/Manila

    restart: unless-stopped
